apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: world-news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: api-gateway-sa
      automountServiceAccountToken: false
      containers:
      - name: api-gateway
        image: <REGISTRY>/world-news/api-gateway:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
