services:
  postgres:
    stop_grace_period: 60s
    image: postgres:18
    environment:
      POSTGRES_USER: worldnews
      POSTGRES_PASSWORD: worldnews
      POSTGRES_DB: worldnews
    ports:
      - "5433:5432"
    volumes:
      - worldnews_pgdata:/var/lib/postgresql
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
    image: world-news-frontend
    environment:
      DATABASE_URL: postgresql://worldnews:worldnews@postgres:5432/worldnews
    ports:
      - "3012:3000"
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  worldnews_pgdata:
