name: Deploy World News

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Stop running containers
        run: |
          if [ -f docker/docker-compose.yml ]; then
            docker compose -f docker/docker-compose.yml down
          fi

      
      - name: Build & start stack
        run: |
          cd docker
          docker compose up -d --build

      
      - name: Cleanup old images
        run: docker system prune -f